Update Stable to v3.4.13 on staging
crosscloudci/etcd-configuration pull request #23
Opened 2020-09-14 16:41 UTC by agentpoyo

## Description
  - v3.4.13 was released on 08/24/2020
  - update stable on integration
  - this build will fail as their own travis-ci is in failed status for several of the build steps: https://travis-ci.com/github/etcd-io/etcd/builds/181139403

## Issues:

 https://github.com/vulk/cncf_ci/issues/344

## How has this been tested:

 - [ ]  Covered by existing integration testing
 - [ ]  Added integration testing to cover
 - [x]  Manually tested on dev.cncf.ci; will fail as their travis-ci shows failed status
 - [ ]  Tested with trigger client against
   - [x]  cidev.cncf.ci
   - [x]  dev.cncf.ci
   - [ ]  staging.cncf.ci
   - [ ]  cncf.ci (production)
 - [ ]  Browser tested on staging.cncf.ci
 - [x]  Have not tested

## Types of changes:
 - [ ]  Bug fix (non-breaking change which fixes an issue)
 - [ ]  New feature (non-breaking change which adds functionality)
 - [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [x] Version update

## Checklist:
  - [ ]  My change requires a change to the documentation
  - [ ]  I have updated the documentation accordingly
  - [x]  No updates required

2020-09-14 17:09 UTC, lixuna commented
@agentpoyo is this working as expected? I would expect to see v3.14.13 for etcd on https://dev.cncf.ci/, but instead it's still showing v3.14.12.

2020-09-16 14:48 UTC, lixuna commented
@agentpoyo is this working as expected? I would expect to see v3.14.13 for etcd on https://dev.cncf.ci/, but instead it's still showing v3.14.12.

2020-09-16 14:48 UTC, lixuna requested changes
@agentpoyo is this working as expected? I would expect to see v3.14.13 for etcd on https://dev.cncf.ci/, but instead it's still showing v3.14.12.

2020-09-16 15:48 UTC, agentpoyo commented
@lixuna 

dev.cncf.ci should reflect etcd 3.4.13 version now. It will show failed status, which is expected due to failed travis-ci failed status on their end.

2020-09-17 14:26 UTC, merged